//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleVisualWebPart.ClockVisualWebPart {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    
    
    public partial class ClockVisualWebPart {
        
        protected global::Microsoft.SharePoint.WebControls.CssRegistration CssRegistration1;
        
        protected global::Microsoft.SharePoint.WebControls.ScriptLink Scriptlink2;
        
        protected global::Microsoft.SharePoint.WebControls.ScriptLink Scriptlink1;
        
        public static implicit operator global::System.Web.UI.TemplateControl(ClockVisualWebPart target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::Microsoft.SharePoint.WebControls.CssRegistration @__BuildControlCssRegistration1() {
            global::Microsoft.SharePoint.WebControls.CssRegistration @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.CssRegistration();
            this.CssRegistration1 = @__ctrl;
            @__ctrl.ID = "CssRegistration1";
            @__ctrl.Name = "/_layouts/15/SimpleVisualWebPart/Styles/ClockVWP.css";
            @__ctrl.After = "corev15.css";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::Microsoft.SharePoint.WebControls.ScriptLink @__BuildControlScriptlink2() {
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.ScriptLink();
            this.Scriptlink2 = @__ctrl;
            @__ctrl.ID = "Scriptlink2";
            @__ctrl.Name = "~SiteCollection/_layouts/15/SimpleVisualWebPart/Scripts/jquery-1.10.2.min.js";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(" "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::Microsoft.SharePoint.WebControls.ScriptLink @__BuildControlScriptlink1() {
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.ScriptLink();
            this.Scriptlink1 = @__ctrl;
            @__ctrl.ID = "Scriptlink1";
            @__ctrl.Name = "~SiteCollection/_layouts/15/SimpleVisualWebPart/Scripts/ClockVWP.js";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(" "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::SimpleVisualWebPart.ClockVisualWebPart.ClockVisualWebPart @__ctrl) {
            global::Microsoft.SharePoint.WebControls.CssRegistration @__ctrl1;
            @__ctrl1 = this.@__BuildControlCssRegistration1();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl2;
            @__ctrl2 = this.@__BuildControlScriptlink2();
            @__parser.AddParsedSubObject(@__ctrl2);
            global::Microsoft.SharePoint.WebControls.ScriptLink @__ctrl3;
            @__ctrl3 = this.@__BuildControlScriptlink1();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Render__control1));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__Render__control1(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            parameterContainer.Controls[0].RenderControl(@__w);
            @__w.Write("\r\n");
            parameterContainer.Controls[1].RenderControl(@__w);
            @__w.Write("\r\n");
            parameterContainer.Controls[2].RenderControl(@__w);
            @__w.Write("\r\n\r\n\r\n<style>\r\n    .clock { color:");
           @__w.Write(ClockTextColor);

            @__w.Write("; background-color:");
                                                 @__w.Write(ClockBackgroundColor);

            @__w.Write("; } \r\n</style>\r\n\r\n\r\n<div class=\"clock\">\r\n<div id=\"Date\"></div>\r\n  <ul>\r\n      <li" +
                    " id=\"hours\"></li>\r\n      <li id=\"point\">:</li>\r\n      <li id=\"min\"></li>\r\n      " +
                    "<li id=\"Li1\">:</li>\r\n      <li id=\"sec\"></li>\r\n  </ul>\r\n</div>");
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
